#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '✅✅✅✅ Check Start!! ✅✅✅✅'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed...';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check Failed... Make the required changes listed above'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Failed Type check... Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ I am committing this now. ✅✅✅✅'
